# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b30116d64d91bdec4626908ea8da46f3f40a7cef38720dc27d22088d0f1c4a31f3fbe0eb03293556619683fbd3800615420be649c3b185926e26dcfa49e5af87

test:
  secret_key_base: 8ed4332977e42dc57b27b6665e05214515738fd49bc12c59410948430e01a6d4ed73ef10c65e8467bfc54c0e224f6d33f89ae6a82e4c68607ca8d1a3e45d188c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
